import villagePng from "../styles/village.png";

export const data = [
  {
    photoUrl: villagePng,
    priceText: "от 8 000 ₽ за сутки",
    description: "1-к. квартира, 75 м², 3/6 эт.",
    place: "с. Эсто-Садок, ул. Горная Карусель, 6 р-н Адлерский",
    size: "1 комната • 75 м²",
    isLiked: false,
    sale: false,
  },
  {
    photoUrl: villagePng,
    priceText: "3 400 000 ₽",
    description: "Гостиница, 90 м²",
    place: "жилой район Адлер, ул. Просвещения, 74Б",
    size: "90 м²",
    isLiked: false,
    sale: "3 100 000 ₽",
  },
  {
    photoUrl: villagePng,
    priceText: "7 887 300 ₽",
    description: "1-к. квартира, 18,3 м², 15/19 эт.",
    place: "ул. Ясногорская, стр. 9 р-н Хостинский",
    size: "1 комната • 8.3 м²",
    isLiked: true,
  },
  {
    photoUrl: villagePng,
    priceText: "280 000 000 ₽",
    description: "Общепит, 800 м²",
    place: "Краснодарский край, Сочи, Курортный пр-т, 47/3р-н Центральный",
    size: "800 м²",
    isLiked: false,
  },
  {
    photoUrl: villagePng,
    priceText: "от 8 000 ₽ за сутки",
    description: "1-к. квартира, 75 м², 3/6 эт.",
    place: "с. Эсто-Садок, ул. Горная Карусель, 6 р-н Адлерский",
    size: "1 комната • 75 м²",
    isLiked: false,
  },
  {
    photoUrl: villagePng,
    priceText: "3 400 000 ₽",
    description: "Гостиница, 90 м²",
    place: "жилой район Адлер, ул. Просвещения, 74Б",
    size: "90 м²",
    isLiked: false,
    sale: "3 100 000 ₽",
  },
  {
    photoUrl: villagePng,
    priceText: "от 8 000 ₽ за сутки",
    description: "1-к. квартира, 75 м², 3/6 эт.",
    place: "с. Эсто-Садок, ул. Горная Карусель, 6 р-н Адлерский",
    size: "1 комната • 75 м²",
    isLiked: false,
  },
  {
    photoUrl: villagePng,
    priceText: "3 400 000 ₽",
    description: "Гостиница, 90 м²",
    place: "жилой район Адлер, ул. Просвещения, 74Б",
    size: "90 м²",
    isLiked: false,
    sale: "3 100 000 ₽",
  },
  {
    photoUrl: villagePng,
    priceText: "7 887 300 ₽",
    description: "1-к. квартира, 18,3 м², 15/19 эт.",
    place: "ул. Ясногорская, стр. 9 р-н Хостинский",
    size: "1 комната • 8.3 м²",
    isLiked: true,
  },
  {
    photoUrl: villagePng,
    priceText: "280 000 000 ₽",
    description: "Общепит, 800 м²",
    place: "Краснодарский край, Сочи, Курортный пр-т, 47/3р-н Центральный",
    size: "800 м²",
    isLiked: false,
  },
  {
    photoUrl: villagePng,
    priceText: "от 8 000 ₽ за сутки",
    description: "1-к. квартира, 75 м², 3/6 эт.",
    place: "с. Эсто-Садок, ул. Горная Карусель, 6 р-н Адлерский",
    size: "1 комната • 75 м²",
    isLiked: false,
  },
  {
    photoUrl: villagePng,
    priceText: "3 400 000 ₽",
    description: "Гостиница, 90 м²",
    place: "жилой район Адлер, ул. Просвещения, 74Б",
    size: "90 м²",
    isLiked: false,
    sale: "3 100 000 ₽",
  },
  {
    photoUrl: villagePng,
    priceText: "от 8 000 ₽ за сутки",
    description: "1-к. квартира, 75 м², 3/6 эт.",
    place: "с. Эсто-Садок, ул. Горная Карусель, 6 р-н Адлерский",
    size: "1 комната • 75 м²",
    isLiked: false,
  },
  {
    photoUrl: villagePng,
    priceText: "3 400 000 ₽",
    description: "Гостиница, 90 м²",
    place: "жилой район Адлер, ул. Просвещения, 74Б",
    size: "90 м²",
    isLiked: false,
    sale: "3 100 000 ₽",
  },
  {
    photoUrl: villagePng,
    priceText: "7 887 300 ₽",
    description: "1-к. квартира, 18,3 м², 15/19 эт.",
    place: "ул. Ясногорская, стр. 9 р-н Хостинский",
    size: "1 комната • 8.3 м²",
    isLiked: true,
  },
  {
    photoUrl: villagePng,
    priceText: "280 000 000 ₽",
    description: "Общепит, 800 м²",
    place: "Краснодарский край, Сочи, Курортный пр-т, 47/3р-н Центральный",
    size: "800 м²",
    isLiked: false,
  },
  {
    photoUrl: villagePng,
    priceText: "от 8 000 ₽ за сутки",
    description: "1-к. квартира, 75 м², 3/6 эт.",
    place: "с. Эсто-Садок, ул. Горная Карусель, 6 р-н Адлерский",
    size: "1 комната • 75 м²",
    isLiked: false,
  },
  {
    photoUrl: villagePng,
    priceText: "3 400 000 ₽",
    description: "Гостиница, 90 м²",
    place: "жилой район Адлер, ул. Просвещения, 74Б",
    size: "90 м²",
    isLiked: false,
    sale: "3 100 000 ₽",
  },
  {
    photoUrl: villagePng,
    priceText: "от 8 000 ₽ за сутки",
    description: "1-к. квартира, 75 м², 3/6 эт.",
    place: "с. Эсто-Садок, ул. Горная Карусель, 6 р-н Адлерский",
    size: "1 комната • 75 м²",
    isLiked: false,
  },
  {
    photoUrl: villagePng,
    priceText: "3 400 000 ₽",
    description: "Гостиница, 90 м²",
    place: "жилой район Адлер, ул. Просвещения, 74Б",
    size: "90 м²",
    isLiked: false,
    sale: "3 100 000 ₽",
  },
  {
    photoUrl: villagePng,
    priceText: "7 887 300 ₽",
    description: "1-к. квартира, 18,3 м², 15/19 эт.",
    place: "ул. Ясногорская, стр. 9 р-н Хостинский",
    size: "1 комната • 8.3 м²",
    isLiked: true,
  },
];
